# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_aKXeerp14aT0z-gFYql-JON1XFSzYqe
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# For reproducible results
np.random.seed(42)

# Generate realistic synthetic data for marketing campaign effectiveness
n = 100
# Example: Spend in thousands ($1k–$100k), Response Rate in percent (2–15%), segmented by Channel
channels = ['Email', 'Social Media', 'TV', 'Search Ads']
data = {
    'Ad_Spend_kUSD': np.random.uniform(10, 100, n),
    'Response_Rate': np.random.uniform(2, 15, n),
    'Channel': np.random.choice(channels, n)
}
df = pd.DataFrame(data)
# Add some positive correlation for effect
df['Response_Rate'] += 0.08 * df['Ad_Spend_kUSD'] + np.random.normal(0, 1.5, n)

# Apply professional seaborn styling
sns.set_style("whitegrid")
sns.set_context("talk") # larger font suitable for presentations

plt.figure(figsize=(8, 8), dpi=64) # 8in x 64dpi = 512px

# Draw scatterplot, color by Channel
ax = sns.scatterplot(
    data=df,
    x='Ad_Spend_kUSD',
    y='Response_Rate',
    hue='Channel',
    palette='viridis',
    s=80,
    edgecolor='black'
)

plt.title("Marketing Campaign Effectiveness by Channel")
plt.xlabel("Ad Spend (Thousands USD)")
plt.ylabel("Response Rate (%)")
plt.legend(title='Channel')
plt.tight_layout()

plt.savefig("chart.png", dpi=64, bbox_inches='tight')  # ensures 512x512 with required settings
plt.close()